# Generated by Django 4.2.29 on 2026-03-10 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], default='stripe', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. The Manhattan Suite Hotel', max_length=200)),
                ('property_type', models.CharField(choices=[('hotel', '🏨 Hotel'), ('vacation_home', '🏠 Vacation Home'), ('cabin', '🏕️ Cabin'), ('apartment', '🏢 Apartment')], default='hotel', max_length=20)),
                ('description', models.TextField(help_text='Full description shown on listing page')),
                ('short_description', models.CharField(help_text='Short blurb for cards', max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('main_image_url', models.URLField(blank=True, help_text='Or use an external image URL')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Free WiFi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Pool')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='Breakfast Included')),
                ('has_free_cancellation', models.BooleanField(default=True, verbose_name='Free Cancellation')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Free Parking')),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('has_hot_tub', models.BooleanField(default=False, verbose_name='Hot Tub')),
                ('has_fire_pit', models.BooleanField(default=False, verbose_name='Fire Pit')),
                ('has_ocean_view', models.BooleanField(default=False, verbose_name='Ocean View')),
                ('has_city_view', models.BooleanField(default=False, verbose_name='City View')),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('max_rooms', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from site')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_deal', models.BooleanField(default=False, help_text='Show in deals section')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_location', models.CharField(blank=True, help_text="e.g. 'New York City · Jan 2026'", max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review_text', models.TextField()),
                ('is_verified', models.BooleanField(default=False, help_text='Mark as verified stay')),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to show on site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stays.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stays.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stays.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Rate', help_text="e.g. 'Standard Rate', 'Summer Special', 'Weekend Rate'", max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='If set, shows as strikethrough (sale price)', max_digits=8, null=True)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='e.g. 18 = 18% off badge shown')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.property')),
            ],
            options={
                'ordering': ['-is_active', 'price_per_night'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
